// Generated by CoffeeScript 1.8.0
(function() {
  var __slice = [].slice;

  require(['controller', 'js/jquery-ui-1.8.16.custom.min.js', 'js/jquery.mobile-1.0.js'], function() {
    var controller, other_modules;
    controller = arguments[0], other_modules = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    return $(document).ready(function() {
      var session;
      $('button').button();
      $('#cardstack').sortable();
      $(document).on('selectstart', function(event) {
        event.preventDefault();
        return false;
      });
      $('body').on('touchmove', function(event) {
        event.preventDefault();
        return false;
      });
      $('#urlentry').on('focus', function(event) {
        return $("#urlentry").val($('#vid').get(0).currentSrc);
      });
      session = new controller.BigController('paint', 'vid');
      document.telestration_session = session;
      return $(window).ready(function() {
        var telescript;
        telescript = session.start_recording();
        return session.start_playing(telescript);
      });
    });
  });

}).call(this);
